const {
	VITE_FIREBASE_API_KEY,
	VITE_FIREBASE_AUTH_DOMAIN,
	VITE_FIREBASE_PROJECT_ID,
	VITE_FIREBASE_STORAGE_BUCKET,
	VITE_FIREBASE_SENDER_ID,
	VITE_FIREBASE_APP_ID,
} = import.meta.env;

export const firebase = {
	API_KEY: (VITE_FIREBASE_API_KEY || "").trim(),
	AUTH_DOMAIN: VITE_FIREBASE_AUTH_DOMAIN,
	PROJECT_ID: VITE_FIREBASE_PROJECT_ID,
	STORAGE_BUCKET: VITE_FIREBASE_STORAGE_BUCKET,
	SENDER_ID: VITE_FIREBASE_SENDER_ID,
	APP_ID: VITE_FIREBASE_APP_ID,
};
